from .catalog import CatalogSyncResult, sync_catalog_data
from .covers import (
    GetComicsCoverResult,
    ensure_remote_cover_image,
    ensure_query_cover_image,
    ensure_reading_path_cover_asset,
    fetch_getcomics_cover,
    parse_getcomics_search_results,
)
from .curation import (
    CURATION_DATA_PATH,
    CurationSyncResult,
    load_curation_payload,
    match_local_issue,
    match_local_series,
    sync_curation_data,
    sync_issue_matches,
    sync_series_matches,
)
from .library import PersistResult, persist_scan, persist_scans, slugify
from .mangapill import (
    MANGAPILL_DATA_PATH,
    fetch_mangapill_chapter_pages,
    fetch_mangapill_series,
    get_mangapill_collection_cover_url,
    sync_mangapill_catalog,
)
from .ingest import (
    ARCHIVE_EXTENSIONS,
    IMAGE_EXTENSIONS,
    ComicMetadata,
    InMemoryJobStore,
    IngestError,
    IngestJobRecord,
    IngestJobRequest,
    IngestService,
    JobStatus,
    PageRecord,
    ScanResult,
    ingest_job_payload,
    discover_sources,
    infer_metadata_from_name,
    scan_archive,
    scan_directory,
    scan_payload,
    scan_source,
)
from .reader import ArchivePage, archive_is_streamable, archive_page_bytes, list_archive_pages

__all__ = [
    "ARCHIVE_EXTENSIONS",
    "ArchivePage",
    "CatalogSyncResult",
    "IMAGE_EXTENSIONS",
    "ComicMetadata",
    "CURATION_DATA_PATH",
    "CurationSyncResult",
    "discover_sources",
    "ensure_remote_cover_image",
    "ensure_query_cover_image",
    "ensure_reading_path_cover_asset",
    "fetch_getcomics_cover",
    "GetComicsCoverResult",
    "InMemoryJobStore",
    "IngestError",
    "IngestJobRecord",
    "IngestJobRequest",
    "IngestService",
    "JobStatus",
    "PageRecord",
    "PersistResult",
    "ScanResult",
    "archive_page_bytes",
    "archive_is_streamable",
    "ingest_job_payload",
    "infer_metadata_from_name",
    "list_archive_pages",
    "load_curation_payload",
    "match_local_issue",
    "match_local_series",
    "MANGAPILL_DATA_PATH",
    "parse_getcomics_search_results",
    "persist_scan",
    "persist_scans",
    "fetch_mangapill_chapter_pages",
    "fetch_mangapill_series",
    "get_mangapill_collection_cover_url",
    "scan_archive",
    "scan_directory",
    "scan_payload",
    "scan_source",
    "slugify",
    "sync_curation_data",
    "sync_catalog_data",
    "sync_issue_matches",
    "sync_series_matches",
    "sync_mangapill_catalog",
]
